parser: '@typescript-eslint/parser'
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: .
  ecmaVersion: 2018
  sourceType: module
rules:
  react/prop-types: [0]
settings:
  react:
    version: detect
